# Generated by Django 4.2 on 2023-04-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='kind',
            field=models.CharField(choices=[('AR', 'Статья'), ('NE', 'Новость')], max_length=2),
        ),
    ]
